### ISSUE TITLE
Get all rendering result~

### ISSUE THREAD

**Issue by xwx0924** [Ruyi-Zha/endosurf#1]
Hi,for the pulling_soft dataset, after training. when i run src/trainer/trainer_endosurf.py with test mode --mode test, i just get the 8 images (tests), how can I get the re-rendering results of the entire 63 images.

**Comment by Ruyi-Zha** [comment]
Hi, thanks for your interest. To render all frames, simply use mode `--mode demo`. For example, run `CUDA_VISIBLE_DEVICES=0 python src/trainer/trainer_endosurf.py \
    --cfg configs/endosurf/baseline/base_pull.yml --mode demo` which will generate 2D images and 3D meshes of all frames. See the updated `README.md` for details.

**Comment by xwx0924** [comment]
thank you~~
