### ISSUE TITLE
Question Regarding PSNR and RMSE

### ISSUE THREAD

**Issue by mhayoz** [Ruyi-Zha/endosurf#3]
I have a question regarding the implementations of PSNR and RMSE in src/trainer/utils.py. In line 368 the RMSE is computed as:
 rmse = (((a - b)**2 * mask).sum() / (mask_sum * 3.0))**0.5

Why is there a factor 3 in the division? I would expect this to be:
rmse = (((a - b)**2 * mask).sum() / (mask.sum()))**0.5

Am I missing something?

**Comment by Ruyi-Zha** [comment]
Hi, thanks for your interest. Yes, you are right it's a small bug and I have fixed it now. I copied the code from `cal_psnr()` but forgot that depth is one channel. Thankfully it does not affect the conclusions.

**Comment by mhayoz** [comment]
Thank you for your answer. Does that mean that the true RMSE is sqrt(3) times higher than reported in the paper?

**Comment by Ruyi-Zha** [comment]
Yes, I think so. However, it does not affect any conclusions we drew because all methods used the same code.

**Comment by mhayoz** [comment]
I see. Thank you for the clarification
