### ISSUE TITLE
How to get the camera parameters in the SCARED dataset?

### ISSUE THREAD

**Issue by huahangc** [Ruyi-Zha/endosurf#6]
Thanks for your exciting work.

In your `preprocess.py` file, I see this code `c2w = np.linalg.inv(np.array(calib_dict["camera-pose"])`,  I think the camera-pose is the c2w matrix and its inverse matrix is the w2c matrix(extrinsic matrix). And at the next line, you use the `c2w = np.linalg.inv(c2w0) @ c2w`, does it means the world center is the first framedata's camera center ? And the others framedata's pose is relative to the first the  framedata's pose ?

And I was wondering  if  the camera pose in these json files corresponding to the left image and how to get the right image camera pose?

Sorry for my poor english. Hope you understand what I mean.

感谢您的精彩工作。

在您的“preprocess.py”文件中，我看到这段代码“c2w = np.linalg.inv（np.array（calib_dict[”camera-pose“]）'，我认为相机姿势是 c2w 矩阵，其逆矩阵是 w2c 矩阵（外参矩阵）。在下一行，你使用 'c2w = np.linalg.inv（c2w0） @ c2w'，这是否意味着世界坐标系的中心是第一个帧的相机中心(也就是说，第一帧的camera pose 是单位阵)？而其他framedata的姿态是相对于第一个framedata的姿态而言的？

我想知道左边图像的相机姿势如何获得右边的图像相机姿势吗？

对不起，我的英语不好。希望你明白我的意思。

**Comment by Ruyi-Zha** [comment]
Thanks for your interest. 

Camera pose: Yes, we set the first frame as the world center and transfer other poses accordingly. 

Right image: We only use left images, processing data as an RGBD sequence. Therefore we don't need to get poses of the right images. If you would like to get the poses of right images, there is `R` and `T` in `data/frame_data/frame_dataxxxx.json` which should be the rotation and translation of right images w.r.t. the left images. You can use them to calculate poses.

**Comment by huahangc** [comment]
Thanks for your replaying.
