### ISSUE TITLE
Do we need dynamic modeling for the SCARED dataset?

### ISSUE THREAD

**Issue by yifliu3** [Ruyi-Zha/endosurf#8]
Dear authors,

Thanks for your great work! When reading the paper, I find that SCARED contains static scenes, which seems to follow the typical satatic setting of NeRF. My questions is do we still need dynamic modelling for this dataset and can other static methods work for this dataset?

**Comment by Ruyi-Zha** [comment]
Thanks for your interest in our work. The SCARED dataset is actually for static stereo matching so there are many other works for this dataset. We disable the deformable part by setting `use_deform` to `False` in configuration files, similar to the NeRF setting.
